import psutil
import os
from logger import get_logger

logger = get_logger("utils_monitor", log_dir="logs", log_file="utils.log")

def obtener_uso_recursos():
    """
    Calcula el consumo total de CPU y RAM del proceso actual (API/Worker)
    Y de todos sus hijos (especialmente Chrome/Chromedriver).
    Retorna un diccionario.
    """
    try:
        # 1. Proceso Padre (Python actual)
        proc_actual = psutil.Process(os.getpid())
        
        # Inicializamos contadores
        total_ram_bytes = proc_actual.memory_info().rss
        total_cpu_percent = proc_actual.cpu_percent(interval=None)
        num_procesos_chrome = 0
        
        # 2. Buscamos recursivamente a todos los hijos (Workers, Drivers, Browsers)
        hijos = proc_actual.children(recursive=True)
        
        for hijo in hijos:
            try:
                # Sumar RAM
                total_ram_bytes += hijo.memory_info().rss
                # Sumar CPU (puede ser > 100% en multicore)
                total_cpu_percent += hijo.cpu_percent(interval=None)
                
                # Contar instancias de Chrome para detectar "Zombies" o carga
                if "chrome" in hijo.name().lower() or "google" in hijo.name().lower():
                    num_procesos_chrome += 1
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                # El proceso murió mientras lo leíamos, lo ignoramos
                pass

        # 3. Conversión a MB
        total_ram_mb = round(total_ram_bytes / (1024 * 1024), 2)
        
        # 4. Info Global del Sistema (Para saber si estamos al límite)
        memoria_virtual = psutil.virtual_memory()
        
        return {
            "ram_uso_mb": total_ram_mb,
            "ram_sistema_percent": memoria_virtual.percent,
            "cpu_proceso_percent": round(total_cpu_percent, 1),
            "cpu_sistema_percent": psutil.cpu_percent(interval=None),
            "workers_chrome_activos": num_procesos_chrome,
            "num_hilos_totales": len(hijos) + 1
        }

    except Exception as e:
        logger.error(f"Error midiendo recursos: {e}")
        return {
            "error": str(e)
        }

def matar_procesos_zombies():
    """
    Mata forzosamente todos los procesos hijos (Chrome/Chromedriver)
    del proceso actual. Útil para la limpieza en cancelaciones.
    """
    try:
        proc_actual = psutil.Process(os.getpid())
        hijos = proc_actual.children(recursive=True)
        
        count = 0
        for hijo in hijos:
            try:
                hijo.kill()
                count += 1
            except:
                pass
        
        if count > 0:
            logger.warning(f"🧹 Se eliminaron {count} procesos huérfanos/zombies.")
    except Exception as e:
        logger.error(f"Error matando zombies: {e}")

# ======================================================
# Catálogo Traductor de Comunas para Selenium
# clave = comuna normalizada
# valor = texto exacto mostrado en el sitio
# ======================================================
# Catálogo Traductor: { "comuna_aplastada": "Nombre Exacto Para Selenium" }
# Catálogo Traductor: { "comuna_aplastada": "Nombre Exacto Para Selenium" }
COMUNAS_TRADUCTOR = {
    "arica": "Arica",
    "camarones": "Camarones",
    "putre": "Putre",
    "general lagos": "General Lagos",
    "iquique": "Iquique",
    "alto hospicio": "Alto Hospicio",
    "pozo almonte": "Pozo Almonte",
    "camina": "Camiña",
    "colchane": "Colchane",
    "huara": "Huara",
    "pica": "Pica",
    "antofagasta": "Antofagasta",
    "mejillones": "Mejillones",
    "sierra gorda": "Sierra Gorda",
    "taltal": "Taltal",
    "calama": "Calama",
    "ollague": "Ollagüe",
    "san pedro de atacama": "San Pedro de Atacama",
    "tocopilla": "Tocopilla",
    "maria elena": "María Elena",
    "copiapo": "Copiapó",
    "caldera": "Caldera",
    "tierra amarilla": "Tierra Amarilla",
    "chanaral": "Chañaral",
    "diego de almagro": "Diego de Almagro",
    "vallenar": "Vallenar",
    "freirina": "Freirina",
    "huasco": "Huasco",
    "alto del carmen": "Alto del Carmen",
    "la serena": "La Serena",
    "serena": "La Serena",
    "coquimbo": "Coquimbo",
    "andacollo": "Andacollo",
    "la higuera": "La Higuera",
    "paihuano": "Paihuano",
    "vicuna": "Vicuña",
    "ovalle": "Ovalle",
    "monte patria": "Monte Patria",
    "combarbala": "Combarbalá",
    "punitaqui": "Punitaqui",
    "rio hurtado": "Río Hurtado",
    "illapel": "Illapel",
    "salamanca": "Salamanca",
    "los vilos": "Los Vilos",
    "canela": "Canela",
    "valparaiso": "Valparaíso",
    "vina del mar": "Viña del Mar",
    "quintero": "Quintero",
    "puchuncavi": "Puchuncaví",
    "quilpue": "Quilpué",
    "villa alemana": "Villa Alemana",
    "casablanca": "Casablanca",
    "concon": "Concón",
    "juan fernandez": "Juan Fernández",
    "la ligua": "La Ligua",
    "petorca": "Petorca",
    "cabildo": "Cabildo",
    "zapallar": "Zapallar",
    "papudo": "Papudo",
    "los andes": "Los Andes",
    "san esteban": "San Esteban",
    "calle larga": "Calle Larga",
    "rinconada": "Rinconada",
    "san felipe": "San Felipe",
    "putaendo": "Putaendo",
    "santa maria": "Santa María",
    "panquehue": "Panquehue",
    "llaillay": "Llaillay",
    "catemu": "Catemu",
    "quillota": "Quillota",
    "la cruz": "La Cruz",
    "calera": "Calera",
    "nogales": "Nogales",
    "hijuelas": "Hijuelas",
    "limache": "Limache",
    "olmue": "Olmué",
    "san antonio": "San Antonio",
    "cartagena": "Cartagena",
    "el quisco": "El Quisco",
    "el tabo": "El Tabo",
    "algarrobo": "Algarrobo",
    "santo domingo": "Santo Domingo",
    "isla de pascua": "Isla de Pascua",
    "santiago": "Santiago",
    "cerrillos": "Cerrillos",
    "cerro navia": "Cerro Navia",
    "conchali": "Conchalí",
    "el bosque": "El Bosque",
    "estacion central": "Estación Central",
    "independencia": "Independencia",
    "la cisterna": "La Cisterna",
    "la florida": "La Florida",
    "la granja": "La Granja",
    "la reina": "La Reina",
    "las condes": "Las Condes",
    "lo barnechea": "Lo Barnechea",
    "lo espejo": "Lo Espejo",
    "lo prado": "Lo Prado",
    "macul": "Macul",
    "maipu": "Maipú",
    "nunoa": "Ñuñoa",
    "pedro aguirre cerda": "Pedro Aguirre Cerda",
    "penalolen": "Peñalolén",
    "providencia": "Providencia",
    "pudahuel": "Pudahuel",
    "puente alto": "Puente Alto",
    "quilicura": "Quilicura",
    "quinta normal": "Quinta Normal",
    "recoleta": "Recoleta",
    "renca": "Renca",
    "san joaquin": "San Joaquín",
    "san miguel": "San Miguel",
    "san ramon": "San Ramón",
    "vitacura": "Vitacura",
    "buin": "Buin",
    "calera de tango": "Calera de Tango",
    "san bernardo": "San Bernardo",
    "paine": "Paine",
    "talagante": "Talagante",
    "el monte": "El Monte",
    "isla de maipo": "Isla de Maipo",
    "padre hurtado": "Padre Hurtado",
    "colina": "Colina",
    "lampa": "Lampa",
    "tiltil": "Tiltil",
    "alhue": "Alhué",
    "curacavi": "Curacaví",
    "maria pinto": "María Pinto",
    "melipilla": "Melipilla",
    "rancagua": "Rancagua",
    "graneros": "Graneros",
    "mostazal": "Mostazal",
    "codegua": "Codegua",
    "machali": "Machalí",
    "olivar": "Olivar",
    "requinoa": "Requínoa",
    "rengo": "Rengo",
    "malloa": "Malloa",
    "quinta de tilcoco": "Quinta de Tilcoco",
    "san vicente": "San Vicente",
    "pichidegua": "Pichidegua",
    "peumo": "Peumo",
    "coltauco": "Coltauco",
    "coinco": "Coinco",
    "donihue": "Doñihue",
    "las cabras": "Las Cabras",
    "san fernando": "San Fernando",
    "chimbarongo": "Chimbarongo",
    "placilla": "Placilla",
    "nancagua": "Nancagua",
    "chepica": "Chépica",
    "santa cruz": "Santa Cruz",
    "lolol": "Lolol",
    "pumanque": "Pumanque",
    "palmilla": "Palmilla",
    "peralillo": "Peralillo",
    "pichilemu": "Pichilemu",
    "navidad": "Navidad",
    "litueche": "Litueche",
    "la estrella": "La Estrella",
    "marchihue": "Marchihue",
    "paredones": "Paredones",
    "talca": "Talca",
    "constitucion": "Constitución",
    "empedrado": "Empedrado",
    "maule": "Maule",
    "pelarco": "Pelarco",
    "pencahue": "Pencahue",
    "rio claro": "Río Claro",
    "san clemente": "San Clemente",
    "san rafael": "San Rafael",
    "curepto": "Curepto",
    "licanten": "Licantén",
    "rauco": "Rauco",
    "sagrada familia": "Sagrada Familia",
    "teno": "Teno",
    "vichuquen": "Vichuquén",
    "curico": "Curicó",
    "colbun": "Colbún",
    "linares": "Linares",
    "longavi": "Longaví",
    "parral": "Parral",
    "retiro": "Retiro",
    "san javier": "San Javier",
    "villa alegre": "Villa Alegre",
    "yerbas buenas": "Yerbas Buenas",
    "chillan": "Chillán",
    "chillan viejo": "Chillán Viejo",
    "bulnes": "Bulnes",
    "cobquecura": "Cobquecura",
    "huechuraba": "Huechuraba",
    "coelemu": "Coelemu",
    "coihueco": "Coihueco",
    "el carmen": "El Carmen",
    "ninhue": "Ninhue",
    "niquen": "Ñiquén",
    "pemuco": "Pemuco",
    "pinto": "Pinto",
    "portezuelo": "Portezuelo",
    "quillon": "Quillón",
    "quirihue": "Quirihue",
    "ranquil": "Ránquil",
    "san carlos": "San Carlos",
    "san fabian": "San Fabián",
    "san ignacio": "San Ignacio",
    "san nicolas": "San Nicolás",
    "treguaco": "Treguaco",
    "yungay": "Yungay",
    "los angeles": "Los Ángeles",
    "antuco": "Antuco",
    "cabrero": "Cabrero",
    "laja": "Laja",
    "mulchen": "Mulchén",
    "nacimiento": "Nacimiento",
    "negrete": "Negrete",
    "quilaco": "Quilaco",
    "quilleco": "Quilleco",
    "san rosendo": "San Rosendo",
    "santa barbara": "Santa Bárbara",
    "tucapel": "Tucapel",
    "temuco": "Temuco",
    "padre las casas": "Padre Las Casas",
    "carahue": "Carahue",
    "cunco": "Cunco",
    "curarrehue": "Curarrehue",
    "freire": "Freire",
    "galvarino": "Galvarino",
    "gorbea": "Gorbea",
    "lautaro": "Lautaro",
    "loncoche": "Loncoche",
    "melipeuco": "Melipeuco",
    "nueva imperial": "Nueva Imperial",
    "pitrufquen": "Pitrufquén",
    "pucon": "Pucón",
    "saavedra": "Saavedra",
    "teodoro schmidt": "Teodoro Schmidt",
    "tolten": "Toltén",
    "villarrica": "Villarrica",
    "valdivia": "Valdivia",
    "corral": "Corral",
    "lanco": "Lanco",
    "los lagos": "Los Lagos",
    "mafil": "Máfil",
    "mariquina": "Mariquina",
    "paillaco": "Paillaco",
    "panguipulli": "Panguipulli",
    "futrono": "Futrono",
    "la union": "La Unión",
    "lago ranco": "Lago Ranco",
    "rio bueno": "Río Bueno",
    "osorno": "Osorno",
    "puyehue": "Puyehue",
    "puerto octay": "Puerto Octay",
    "purranque": "Purranque",
    "rio negro": "Río Negro",
    "san juan de la costa": "San Juan de la Costa",
    "san pablo": "San Pablo",
    "castro": "Castro",
    "ancud": "Ancud",
    "chonchi": "Chonchi",
    "curaco de velez": "Curaco de Vélez",
    "dalcahue": "Dalcahue",
    "puqueldon": "Puqueldón",
    "queilen": "Queilén",
    "quinchao": "Quinchao",
    "quellon": "Quellón",
    "calbuco": "Calbuco",
    "fresia": "Fresia",
    "frutillar": "Frutillar",
    "los muermos": "Los Muermos",
    "llanquihue": "Llanquihue",
    "maullin": "Maullín",
    "puerto montt": "Puerto Montt",
    "puerto varas": "Puerto Varas",
    "cochamo": "Cochamó",
    "hualaihue": "Hualaihué",
    "chaiten": "Chaitén",
    "futaleufu": "Futaleufú",
    "palena": "Palena",
    "aysen": "Aysén",
    "cisnes": "Cisnes",
    "guaitecas": "Guaitecas",
    "coihaique": "Coyhaique",
    "lago verde": "Lago Verde",
    "chile chico": "Chile Chico",
    "rio ibanez": "Río Ibáñez",
    "cochrane": "Cochrane",
    "o'higgins": "O'Higgins",
    "tortel": "Tortel",
    "punta arenas": "Punta Arenas",
    "laguna blanca": "Laguna Blanca",
    "rio verde": "Río Verde",
    "san gregorio": "San Gregorio",
    "porvenir": "Porvenir",
    "primavera": "Primavera",
    "timaukel": "Timaukel",
    "natales": "Natales",
    "torres del paine": "Torres del Paine",
    "cabo de hornos": "Cabo de Hornos",
    "antartica": "Antártica"
}


COMUNAS_DATA = [
    {"value": "278", "label": "Algarrobo"}, {"value": "209", "label": "Alhué"}, {"value": "138", "label": "Alto Biobío"}, 
    {"value": "296", "label": "Alto del Carmen"}, {"value": "206", "label": "Alto Hospicio"}, {"value": "45", "label": "Ancud"}, 
    {"value": "199", "label": "Andacollo"}, {"value": "75", "label": "Angol"}, {"value": "3", "label": "Antártica"}, 
    {"value": "141", "label": "Antofagasta"}, {"value": "135", "label": "Antuco"}, {"value": "111", "label": "Arauco"}, 
    {"value": "44", "label": "Arica"}, {"value": "297", "label": "Aysén"}, {"value": "208", "label": "Buin"}, 
    {"value": "148", "label": "Bulnes"}, {"value": "266", "label": "Cabildo"}, {"value": "298", "label": "Cabo de Hornos"}, 
    {"value": "132", "label": "Cabrero"}, {"value": "142", "label": "Calama"}, {"value": "48", "label": "Calbuco"}, 
    {"value": "99", "label": "Caldera"}, {"value": "256", "label": "Calera de Tango"}, {"value": "288", "label": "Calle Larga"}, 
    {"value": "299", "label": "Camarones"}, {"value": "300", "label": "Camiña"}, {"value": "201", "label": "Canela"}, 
    {"value": "112", "label": "Cañete"}, {"value": "82", "label": "Carahue"}, {"value": "279", "label": "Cartagena"}, 
    {"value": "285", "label": "Casablanca"}, {"value": "46", "label": "Castro"}, {"value": "263", "label": "Catemu"}, 
    {"value": "21", "label": "Cauquenes"}, {"value": "229", "label": "Cerrillos"}, {"value": "244", "label": "Cerro Navia"}, 
    {"value": "71", "label": "Chaitén"}, {"value": "301", "label": "Chanco"}, {"value": "101", "label": "Chañaral"}, 
    {"value": "163", "label": "Chépica"}, {"value": "127", "label": "Chiguayante"}, {"value": "302", "label": "Chile Chico"}, 
    {"value": "149", "label": "Chillán"}, {"value": "130", "label": "Chillán Viejo"}, {"value": "183", "label": "Chimbarongo"}, 
    {"value": "96", "label": "Cholchol"}, {"value": "49", "label": "Chonchi"}, {"value": "303", "label": "Cisnes"}, 
    {"value": "153", "label": "Cobquecura"}, {"value": "64", "label": "Cochamó"}, {"value": "304", "label": "Cochrane"}, 
    {"value": "164", "label": "Codegua"}, {"value": "116", "label": "Coelemu"}, {"value": "152", "label": "Coihueco"}, 
    {"value": "160", "label": "Coinco"}, {"value": "9", "label": "Colbún"}, {"value": "305", "label": "Colchane"}, 
    {"value": "216", "label": "Colina"}, {"value": "306", "label": "Collipulli"}, {"value": "168", "label": "Coltauco"}, 
    {"value": "307", "label": "Combarbalá"}, {"value": "123", "label": "Concepción"}, {"value": "219", "label": "Conchalí"}, 
    {"value": "264", "label": "Concón"}, {"value": "26", "label": "Constitución"}, {"value": "137", "label": "Contulmo"}, 
    {"value": "100", "label": "Copiapó"}, {"value": "191", "label": "Coquimbo"}, {"value": "117", "label": "Coronel"}, 
    {"value": "34", "label": "Corral"}, {"value": "140", "label": "Coyhaique"}, {"value": "76", "label": "Cunco"}, 
    {"value": "88", "label": "Curacautín"}, {"value": "220", "label": "Curacaví"}, {"value": "67", "label": "Curaco de Vélez"}, 
    {"value": "308", "label": "Curanilahue"}, {"value": "89", "label": "Curarrehue"}, {"value": "309", "label": "Curepto"}, 
    {"value": "10", "label": "Curicó"}, {"value": "66", "label": "Dalcahue"}, {"value": "104", "label": "Diego de Almagro"}, 
    {"value": "165", "label": "Doñihue"}, {"value": "230", "label": "El Bosque"}, {"value": "122", "label": "El Carmen"}, 
    {"value": "221", "label": "El Monte"}, {"value": "280", "label": "El Quisco"}, {"value": "267", "label": "El Tabo"}, 
    {"value": "310", "label": "Empedrado"}, {"value": "311", "label": "Ercilla"}, {"value": "257", "label": "Estación Central"}, 
    {"value": "133", "label": "Florida"}, {"value": "78", "label": "Freire"}, {"value": "102", "label": "Freirina"}, 
    {"value": "69", "label": "Fresia"}, {"value": "53", "label": "Frutillar"}, {"value": "54", "label": "Futaleufú"}, 
    {"value": "35", "label": "Futrono"}, {"value": "312", "label": "Galvarino"}, {"value": "313", "label": "General Lagos"}, 
    {"value": "79", "label": "Gorbea"}, {"value": "169", "label": "Graneros"}, {"value": "314", "label": "Guaitecas"}, 
    {"value": "272", "label": "Hijuelas"}, {"value": "68", "label": "Hualaihué"}, {"value": "13", "label": "Hualañé"}, 
    {"value": "118", "label": "Hualpén"}, {"value": "119", "label": "Hualqui"}, {"value": "315", "label": "Huara"}, 
    {"value": "98", "label": "Huasco"}, {"value": "239", "label": "Huechuraba"}, {"value": "202", "label": "Illapel"}, 
    {"value": "252", "label": "Independencia"}, {"value": "205", "label": "Iquique"}, {"value": "253", "label": "Isla de Maipo"}, 
    {"value": "316", "label": "Isla de Pascua"}, {"value": "295", "label": "Juan Fernández"}, {"value": "317", "label": "La Calera"}, 
    {"value": "245", "label": "La Cisterna"}, {"value": "268", "label": "La Cruz"}, {"value": "184", "label": "La Estrella"}, 
    {"value": "240", "label": "La Florida"}, {"value": "231", "label": "La Granja"}, {"value": "203", "label": "La Higuera"}, 
    {"value": "273", "label": "La Ligua"}, {"value": "241", "label": "La Pintana"}, {"value": "222", "label": "La Reina"}, 
    {"value": "195", "label": "La Serena"}, {"value": "36", "label": "La Unión"}, {"value": "42", "label": "Lago Ranco"}, 
    {"value": "318", "label": "Lago Verde"}, {"value": "319", "label": "Laguna Blanca"}, {"value": "106", "label": "Laja"}, 
    {"value": "210", "label": "Lampa"}, {"value": "32", "label": "Lanco"}, {"value": "180", "label": "Las Cabras"}, 
    {"value": "242", "label": "Las Condes"}, {"value": "83", "label": "Lautaro"}, {"value": "107", "label": "Lebu"}, 
    {"value": "18", "label": "Licantén"}, {"value": "269", "label": "Limache"}, {"value": "14", "label": "Linares"}, 
    {"value": "170", "label": "Litueche"}, {"value": "58", "label": "Llanquihue"}, {"value": "281", "label": "Llay-Llay"}, 
    {"value": "250", "label": "Lo Barnechea"}, {"value": "232", "label": "Lo Espejo"}, {"value": "223", "label": "Lo Prado"}, 
    {"value": "188", "label": "Lolol"}, {"value": "84", "label": "Loncoche"}, {"value": "15", "label": "Longaví"}, 
    {"value": "87", "label": "Lonquimay"}, {"value": "320", "label": "Los Álamos"}, {"value": "282", "label": "Los Andes"}, 
    {"value": "128", "label": "Los Ángeles"}, {"value": "39", "label": "Los Lagos"}, {"value": "59", "label": "Los Muermos"}, 
    {"value": "321", "label": "Los Sauces"}, {"value": "196", "label": "Los Vilos"}, {"value": "108", "label": "Lota"}, 
    {"value": "322", "label": "Lumaco"}, {"value": "166", "label": "Machalí"}, {"value": "211", "label": "Macul"}, 
    {"value": "33", "label": "Máfil"}, {"value": "212", "label": "Maipú"}, {"value": "161", "label": "Malloa"}, 
    {"value": "323", "label": "Marchigüe"}, {"value": "324", "label": "María Elena"}, {"value": "246", "label": "María Pinto"}, 
    {"value": "40", "label": "Mariquina"}, {"value": "5", "label": "Maule"}, {"value": "63", "label": "Maullín"}, 
    {"value": "144", "label": "Mejillones"}, {"value": "325", "label": "Melipeuco"}, {"value": "233", "label": "Melipilla"}, 
    {"value": "11", "label": "Molina"}, {"value": "198", "label": "Monte Patria"}, {"value": "171", "label": "Mostazal"}, 
    {"value": "326", "label": "Mulchén"}, {"value": "124", "label": "Nacimiento"}, {"value": "172", "label": "Nancagua"}, 
    {"value": "2", "label": "Natales"}, {"value": "167", "label": "Navidad"}, {"value": "120", "label": "Negrete"}, 
    {"value": "327", "label": "Ninhue"}, {"value": "270", "label": "Nogales"}, {"value": "92", "label": "Nueva Imperial"}, 
    {"value": "157", "label": "Ñiquén"}, {"value": "213", "label": "Ñuñoa"}, {"value": "328", "label": "O'Higgins"}, 
    {"value": "162", "label": "Olivar"}, {"value": "329", "label": "Ollagüe"}, {"value": "261", "label": "Olmué"}, 
    {"value": "47", "label": "Osorno"}, {"value": "192", "label": "Ovalle"}, {"value": "254", "label": "Padre Hurtado"}, 
    {"value": "93", "label": "Padre las Casas"}, {"value": "194", "label": "Paihuano"}, {"value": "37", "label": "Paillaco"}, 
    {"value": "214", "label": "Paine"}, {"value": "70", "label": "Palena"}, {"value": "173", "label": "Palmilla"}, 
    {"value": "43", "label": "Panguipulli"}, {"value": "283", "label": "Panquehue"}, {"value": "265", "label": "Papudo"}, 
    {"value": "177", "label": "Paredones"}, {"value": "12", "label": "Parral"}, {"value": "259", "label": "Pedro Aguirre Cerda"}, 
    {"value": "16", "label": "Pelarco"}, {"value": "19", "label": "Pelluhue"}, {"value": "113", "label": "Pemuco"}, 
    {"value": "20", "label": "Pencahue"}, {"value": "110", "label": "Penco"}, {"value": "224", "label": "Peñaflor"}, 
    {"value": "234", "label": "Peñalolén"}, {"value": "178", "label": "Peralillo"}, {"value": "95", "label": "Perquenco"}, 
    {"value": "330", "label": "Petorca"}, {"value": "158", "label": "Peumo"}, {"value": "204", "label": "Pica"}, 
    {"value": "181", "label": "Pichidegua"}, {"value": "179", "label": "Pichilemu"}, {"value": "147", "label": "Pinto"}, 
    {"value": "217", "label": "Pirque"}, {"value": "90", "label": "Pitrufquén"}, {"value": "190", "label": "Placilla"}, 
    {"value": "125", "label": "Portezuelo"}, {"value": "331", "label": "Porvenir"}, {"value": "207", "label": "Pozo Almonte"}, 
    {"value": "332", "label": "Primavera"}, {"value": "247", "label": "Providencia"}, {"value": "286", "label": "Puchuncaví"}, 
    {"value": "77", "label": "Pucón"}, {"value": "225", "label": "Pudahuel"}, {"value": "248", "label": "Puente Alto"}, 
    {"value": "60", "label": "Puerto Montt"}, {"value": "61", "label": "Puerto Octay"}, {"value": "62", "label": "Puerto Varas"}, 
    {"value": "189", "label": "Pumanque"}, {"value": "333", "label": "Punitaqui"}, {"value": "1", "label": "Punta Arenas"}, 
    {"value": "55", "label": "Puqueldón"}, {"value": "334", "label": "Purén"}, {"value": "56", "label": "Purranque"}, 
    {"value": "274", "label": "Putaendo"}, {"value": "335", "label": "Putre"}, {"value": "50", "label": "Puyehue"}, 
    {"value": "51", "label": "Queilén"}, {"value": "52", "label": "Quellón"}, {"value": "65", "label": "Quemchi"}, 
    {"value": "336", "label": "Quilaco"}, {"value": "235", "label": "Quilicura"}, {"value": "337", "label": "Quilleco"}, 
    {"value": "150", "label": "Quillón"}, {"value": "275", "label": "Quillota"}, {"value": "271", "label": "Quilpué"}, 
    {"value": "74", "label": "Quinchao"}, {"value": "187", "label": "Quinta de Tilcoco"}, {"value": "255", "label": "Quinta Normal"}, 
    {"value": "276", "label": "Quintero"}, {"value": "338", "label": "Quirihue"}, {"value": "174", "label": "Rancagua"}, 
    {"value": "121", "label": "Ránquil"}, {"value": "7", "label": "Rauco"}, {"value": "226", "label": "Recoleta"}, 
    {"value": "339", "label": "Renaico"}, {"value": "215", "label": "Renca"}, {"value": "159", "label": "Rengo"}, 
    {"value": "175", "label": "Requínoa"}, {"value": "31", "label": "Retiro"}, {"value": "284", "label": "Rinconada"}, 
    {"value": "41", "label": "Río Bueno"}, {"value": "22", "label": "Río Claro"}, {"value": "200", "label": "Río Hurtado"}, 
    {"value": "340", "label": "Río Ibáñez"}, {"value": "72", "label": "Río Negro"}, {"value": "341", "label": "Río Verde"}, 
    {"value": "17", "label": "Romeral"}, {"value": "85", "label": "Saavedra"}, {"value": "30", "label": "Sagrada Familia"}, 
    {"value": "197", "label": "Salamanca"}, {"value": "289", "label": "San Antonio"}, {"value": "251", "label": "San Bernardo"}, 
    {"value": "151", "label": "San Carlos"}, {"value": "27", "label": "San Clemente"}, {"value": "290", "label": "San Esteban"}, 
    {"value": "154", "label": "San Fabián"}, {"value": "287", "label": "San Felipe"}, {"value": "186", "label": "San Fernando"}, 
    {"value": "342", "label": "San Gregorio"}, {"value": "155", "label": "San Ignacio"}, {"value": "24", "label": "San Javier"}, 
    {"value": "249", "label": "San Joaquín"}, {"value": "258", "label": "San José de Maipo"}, {"value": "73", "label": "San Juan de la Costa"}, 
    {"value": "243", "label": "San Miguel"}, {"value": "156", "label": "San Nicolás"}, {"value": "57", "label": "San Pablo"}, 
    {"value": "236", "label": "San Pedro"}, {"value": "145", "label": "San Pedro de Atacama"}, {"value": "134", "label": "San Pedro de la Paz"}, 
    {"value": "25", "label": "San Rafael"}, {"value": "237", "label": "San Ramón"}, {"value": "343", "label": "San Rosendo"}, 
    {"value": "185", "label": "San Vicente"}, {"value": "139", "label": "Santa Bárbara"}, {"value": "182", "label": "Santa Cruz"}, 
    {"value": "129", "label": "Santa Juana"}, {"value": "291", "label": "Santa María"}, {"value": "227", "label": "Santiago"}, 
    {"value": "293", "label": "Santo Domingo"}, {"value": "146", "label": "Sierra Gorda"}, {"value": "238", "label": "Talagante"}, 
    {"value": "8", "label": "Talca"}, {"value": "126", "label": "Talcahuano"}, {"value": "344", "label": "Taltal"}, 
    {"value": "80", "label": "Temuco"}, {"value": "6", "label": "Teno"}, {"value": "94", "label": "Teodoro Schmidt"}, 
    {"value": "105", "label": "Tierra Amarilla"}, {"value": "218", "label": "Til Til"}, {"value": "345", "label": "Timaukel"}, 
    {"value": "346", "label": "Tirúa"}, {"value": "143", "label": "Tocopilla"}, {"value": "347", "label": "Toltén"}, 
    {"value": "109", "label": "Tomé"}, {"value": "4", "label": "Torres del Paine"}, {"value": "348", "label": "Tortel"}, 
    {"value": "97", "label": "Traiguén"}, {"value": "349", "label": "Treguaco"}, {"value": "136", "label": "Tucapel"}, 
    {"value": "38", "label": "Valdivia"}, {"value": "103", "label": "Vallenar"}, {"value": "260", "label": "Valparaíso"}, 
    {"value": "23", "label": "Vichuquén"}, {"value": "86", "label": "Victoria"}, {"value": "193", "label": "Vicuña"}, 
    {"value": "81", "label": "Vilcún"}, {"value": "28", "label": "Villa Alegre"}, {"value": "294", "label": "Villa Alemana"}, 
    {"value": "91", "label": "Villarrica"}, {"value": "292", "label": "Viña del Mar"}, {"value": "228", "label": "Vitacura"}, 
    {"value": "29", "label": "Yerbas Buenas"}, {"value": "114", "label": "Yumbel"}, {"value": "115", "label": "Yungay"}, 
    {"value": "277", "label": "Zapallar"}
]