name: Despliegue a QA

on:
  push:
    branches:
      - qa

jobs:
  deploy-qa:
    name: Desplegar en Servidor QA
    runs-on: ubuntu-latest

    steps:
      - name: Conectar por SSH y Ejecutar Comandos en QA
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.QA_SERVER_HOST }}
          username: ${{ secrets.QA_SERVER_USER }}
          key: ${{ secrets.QA_SERVER_SSH_KEY }}
          script: |
            # 1. Moverse a la carpeta exacta en el servidor QA
            cd "/home/soporte/Escritorio/API TEST"
            
            # 2. Asegurarse de estar en la rama correcta y descargar cambios
            git checkout qa
            git pull origin qa
            
            # 3. Activar entorno virtual e instalar dependencias
            source env/bin/activate
            pip install -r requirements.txt
            
            # 4. Reiniciar PM2
            pm2 restart api_hp_test