name: Despliegue a QA (Self-Hosted)

on:
  push:
    branches:
      - qa

jobs:
  deploy-qa:
    name: Desplegar en Servidor QA
    # Cambiamos 'ubuntu-latest' por tu runner propio
    runs-on: self-hosted 

    steps:
      # Este paso descarga el código en la carpeta de trabajo del runner
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ejecutar comandos de despliegue local
        run: |
          # 1. Moverse a la carpeta del proyecto
          # Nota: El runner ya está en el servidor, solo asegúrate de la ruta
          cd "/home/soporte/Escritorio/API TEST"
          
          # 2. Actualizar código
          git checkout qa
          git pull origin qa
          
          # 3. Entorno virtual y dependencias
          # Usamos la ruta completa del env para evitar errores de contexto
          source env/bin/activate
          pip install -r requirements.txt
          
          # 4. Reiniciar proceso
          pm2 restart api_hp_test
